### ISSUE TITLE
suggestion: The Theme is Perfect, but Some Aesthetic Aspects Aren't to My Liking

### ISSUE THREAD

**Issue by F3feRP** [prplwtf/Nebula#46]
The theme has many appreciated functions, and after talking with Ivy, I understand that she's working on customizing the sidebar so that add-ons don't appear in a tab called "more." However, what leaves me wanting more is the theme's aesthetics. There are many things I would prefer to be simpler and cleaner, like the sidebar. To give you an example of what I personally like, it would be a sidebar like the one in the Nova theme. I’m not saying the current one is bad—I don't even know if your other clients share my opinion—but I would prefer a sidebar of that style. Besides that, I really like the rest of the theme both aesthetically and functionally.

Another suggestion would be to add an (i) next to the colors in the color palette section that, when hovered over, explains what they modify. It’s quite tedious to have to click everything to see what changes.

Other than that, I have nothing more to comment on. You've worked very hard, and it’s a spectacular theme—economical and undoubtedly the best I've seen at such a ridiculously low price, especially when it's discounted. Thank you very much, Ivy, for creating this gem.

**Comment by prplwtf** [comment]
Thanks for your feedback and kind words, I highly appreciate it.

I'll try to get some color palette labeling going in future releases, but Nebula currently has a huge backlog so I can't work on everything at once. This suggestion can be further discussed in #15 .

The style your looking for with the sidebar should be possible, but I feel like it might be best to refrain from copying from other themes. I might come up with some alternative button types which I'll create a new issue for.

I'm currently thinking of ways to go about automatically creating new sidebar entries instead of a "more" tab and it might come with some technical challenges with highlighting the active page, I'll keep trying to get something working for a future release and also making the current "more" option better.

I'll close this issue and create new issues for some specific features you mentioned (for better issue tracking on my part).

**Comment by prplwtf** [comment]
Nebula has been such an awesome thing to work on and giving the community a say in the future of the project is something I'd never say no to. Definitely looking forward to your future suggestions!

**Comment by Kristiansito** [comment]
> "I'm currently thinking of ways to go about automatically creating new sidebar entries instead of a "more" tab and it might come with some technical challenges with highlighting the active page, I'll keep trying to get something working for a future release and also making the current "more" option better."

> Can't wait to see this working, keep up the good work!

**Comment by Kristiansito** [comment]
> "I'm currently thinking of ways to go about automatically creating new sidebar entries instead of a "more" tab and it might come with some technical challenges with highlighting the active page, I'll keep trying to get something working for a future release and also making the current "more" option better."

Can't wait to see this working, keep up the good work!

**Comment by Kristiansito** [comment]
> I'm currently thinking of ways to go about automatically creating new sidebar entries instead of a "more" tab and it might come with some technical challenges with highlighting the active page, I'll keep trying to get something working for a future release and also making the current "more" option better.

Can't wait to see this working, keep up the good work!
